///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Genesis.Provider.Legacy.Desktop.RanorexTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Create_ReleasePO recording.
    /// </summary>
    [TestModule("c2e15e46-7564-46df-8a4d-481f1405568c", ModuleType.Recording, 1)]
    public partial class Create_ReleasePO : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Genesis_Provider_Legacy_Desktop_RanorexTestsRepository repository.
        /// </summary>
        public static Genesis_Provider_Legacy_Desktop_RanorexTestsRepository repo = Genesis_Provider_Legacy_Desktop_RanorexTestsRepository.Instance;

        static Create_ReleasePO instance = new Create_ReleasePO();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Create_ReleasePO()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Create_ReleasePO Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\Genesis Automation Ltd\\Genesis Automation\\GenesisAutomation.exe' in normal mode. Return value bound to $.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files (x86)\\Genesis Automation Ltd\\Genesis Automation\\GenesisAutomation.exe", "", "C:\\Program Files (x86)\\Genesis Automation Ltd\\Genesis Automation", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmLogin.NoCapsMsgTextBoxMaskBox' at 150;6.", repo.FrmLogin.NoCapsMsgTextBoxMaskBoxInfo, new RecordItemIndex(1));
            repo.FrmLogin.NoCapsMsgTextBoxMaskBox.Click("150;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'password1' with focus on 'FrmLogin.NoCapsMsgTextBoxMaskBox'.", repo.FrmLogin.NoCapsMsgTextBoxMaskBoxInfo, new RecordItemIndex(2));
            repo.FrmLogin.NoCapsMsgTextBoxMaskBox.PressKeys("password1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmLogin.SignIn' at 83;12.", repo.FrmLogin.SignInInfo, new RecordItemIndex(3));
            repo.FrmLogin.SignIn.Click("83;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.CreateRequisition' at 49;18.", repo.FrmMain.CreateRequisitionInfo, new RecordItemIndex(4));
            repo.FrmMain.CreateRequisition.Click("49;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.Open' at 10;12.", repo.FrmCreateRequisition.OpenInfo, new RecordItemIndex(5));
            repo.FrmCreateRequisition.Open.Click("10;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.DescriptionRow9' at 101;16.", repo.GenesisAutomation.DescriptionRow9Info, new RecordItemIndex(6));
            repo.GenesisAutomation.DescriptionRow9.Click("101;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.Open1' at 7;14.", repo.FrmCreateRequisition.Open1Info, new RecordItemIndex(7));
            repo.FrmCreateRequisition.Open1.Click("7;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation.DescriptionRow0' at 116;12.", repo.GenesisAutomation.DescriptionRow0Info, new RecordItemIndex(8));
            repo.GenesisAutomation.DescriptionRow0.Click("116;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.AddRequisition' at 121;16.", repo.FrmCreateRequisition.AddRequisitionInfo, new RecordItemIndex(9));
            repo.FrmCreateRequisition.AddRequisition.Click("121;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCreateRequisition.Confirm' at 100;12.", repo.FrmCreateRequisition.ConfirmInfo, new RecordItemIndex(10));
            repo.FrmCreateRequisition.Confirm.Click("100;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GenesisAutomation1.ButtonOK' at 43;0.", repo.GenesisAutomation1.ButtonOKInfo, new RecordItemIndex(11));
            repo.GenesisAutomation1.ButtonOK.Click("43;0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.NewOrders' at 75;12.", repo.FrmMain.NewOrdersInfo, new RecordItemIndex(12));
            repo.FrmMain.NewOrders.Click("75;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.ReleaseRow0' at 28;12.", repo.FrmMain.ReleaseRow0Info, new RecordItemIndex(13));
            repo.FrmMain.ReleaseRow0.Click("28;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PurchaseOrder.ButtonOK' at 39;10.", repo.PurchaseOrder.ButtonOKInfo, new RecordItemIndex(14));
            repo.PurchaseOrder.ButtonOK.Click("39;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.Ribbon' at 1904;24.", repo.FrmMain.RibbonInfo, new RecordItemIndex(15));
            repo.FrmMain.Ribbon.Click("1904;24");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
