///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Genesis.Provider.Legacy.Desktop.RanorexTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Genesis_Provider_Legacy_Desktop_RanorexTestsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b589f26a-272d-4afa-92e6-d44d7c9209ae")]
    public partial class Genesis_Provider_Legacy_Desktop_RanorexTestsRepository : RepoGenBaseFolder
    {
        static Genesis_Provider_Legacy_Desktop_RanorexTestsRepository instance = new Genesis_Provider_Legacy_Desktop_RanorexTestsRepository();
        Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.FrmLoginAppFolder _frmlogin;
        Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.FrmMainAppFolder _frmmain;
        Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.FrmCreateRequisitionAppFolder _frmcreaterequisition;
        Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.GenesisAutomationAppFolder _genesisautomation;
        Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.GenesisAutomation1AppFolder _genesisautomation1;
        Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.PurchaseOrderAppFolder _purchaseorder;

        /// <summary>
        /// Gets the singleton class instance representing the Genesis_Provider_Legacy_Desktop_RanorexTestsRepository element repository.
        /// </summary>
        [RepositoryFolder("b589f26a-272d-4afa-92e6-d44d7c9209ae")]
        public static Genesis_Provider_Legacy_Desktop_RanorexTestsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Genesis_Provider_Legacy_Desktop_RanorexTestsRepository() 
            : base("Genesis_Provider_Legacy_Desktop_RanorexTestsRepository", "/", null, 0, false, "b589f26a-272d-4afa-92e6-d44d7c9209ae", ".\\RepositoryImages\\Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryb589f26a.rximgres")
        {
            _frmlogin = new Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.FrmLoginAppFolder(this);
            _frmmain = new Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.FrmMainAppFolder(this);
            _frmcreaterequisition = new Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.FrmCreateRequisitionAppFolder(this);
            _genesisautomation = new Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.GenesisAutomationAppFolder(this);
            _genesisautomation1 = new Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.GenesisAutomation1AppFolder(this);
            _purchaseorder = new Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.PurchaseOrderAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b589f26a-272d-4afa-92e6-d44d7c9209ae")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FrmLogin folder.
        /// </summary>
        [RepositoryFolder("f237b9ce-bfa8-4477-b558-fefeee9ee08a")]
        public virtual Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.FrmLoginAppFolder FrmLogin
        {
            get { return _frmlogin; }
        }

        /// <summary>
        /// The FrmMain folder.
        /// </summary>
        [RepositoryFolder("cfcd86cd-7df9-42de-93f8-236376121663")]
        public virtual Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.FrmMainAppFolder FrmMain
        {
            get { return _frmmain; }
        }

        /// <summary>
        /// The FrmCreateRequisition folder.
        /// </summary>
        [RepositoryFolder("e601b729-5bb5-46a5-b59e-a17cbf750ccc")]
        public virtual Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.FrmCreateRequisitionAppFolder FrmCreateRequisition
        {
            get { return _frmcreaterequisition; }
        }

        /// <summary>
        /// The GenesisAutomation folder.
        /// </summary>
        [RepositoryFolder("51d12379-fb49-4f4b-ba80-e2fe15df1ee0")]
        public virtual Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.GenesisAutomationAppFolder GenesisAutomation
        {
            get { return _genesisautomation; }
        }

        /// <summary>
        /// The GenesisAutomation1 folder.
        /// </summary>
        [RepositoryFolder("509ff017-4497-44fc-8951-e4ad111bb67a")]
        public virtual Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.GenesisAutomation1AppFolder GenesisAutomation1
        {
            get { return _genesisautomation1; }
        }

        /// <summary>
        /// The PurchaseOrder folder.
        /// </summary>
        [RepositoryFolder("285e36c0-a8bf-490b-9839-f0d08abfb535")]
        public virtual Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders.PurchaseOrderAppFolder PurchaseOrder
        {
            get { return _purchaseorder; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Genesis_Provider_Legacy_Desktop_RanorexTestsRepositoryFolders
    {
        /// <summary>
        /// The FrmLoginAppFolder folder.
        /// </summary>
        [RepositoryFolder("f237b9ce-bfa8-4477-b558-fefeee9ee08a")]
        public partial class FrmLoginAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nocapsmsgtextboxmaskboxInfo;
            RepoItemInfo _signinInfo;

            /// <summary>
            /// Creates a new FrmLogin  folder.
            /// </summary>
            public FrmLoginAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FrmLogin", "/form[@controlname='FrmLogin']", parentFolder, 30000, null, true, "f237b9ce-bfa8-4477-b558-fefeee9ee08a", "")
            {
                _nocapsmsgtextboxmaskboxInfo = new RepoItemInfo(this, "NoCapsMsgTextBoxMaskBox", "?/?/element[@controlname='txtPassword']/text[@controltypename='NoCapsMsgTextBoxMaskBox']", 30000, null, "af978f50-6723-4387-93c6-f7187d64254d");
                _signinInfo = new RepoItemInfo(this, "SignIn", "?/?/element[@controlname='btnLogin']/button[@accessiblename='Sign in']", 30000, null, "e82f67d4-76f8-4972-ae4e-d14e4eb07c2f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f237b9ce-bfa8-4477-b558-fefeee9ee08a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f237b9ce-bfa8-4477-b558-fefeee9ee08a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NoCapsMsgTextBoxMaskBox item.
            /// </summary>
            [RepositoryItem("af978f50-6723-4387-93c6-f7187d64254d")]
            public virtual Ranorex.Text NoCapsMsgTextBoxMaskBox
            {
                get
                {
                    return _nocapsmsgtextboxmaskboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NoCapsMsgTextBoxMaskBox item info.
            /// </summary>
            [RepositoryItemInfo("af978f50-6723-4387-93c6-f7187d64254d")]
            public virtual RepoItemInfo NoCapsMsgTextBoxMaskBoxInfo
            {
                get
                {
                    return _nocapsmsgtextboxmaskboxInfo;
                }
            }

            /// <summary>
            /// The SignIn item.
            /// </summary>
            [RepositoryItem("e82f67d4-76f8-4972-ae4e-d14e4eb07c2f")]
            public virtual Ranorex.Button SignIn
            {
                get
                {
                    return _signinInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SignIn item info.
            /// </summary>
            [RepositoryItemInfo("e82f67d4-76f8-4972-ae4e-d14e4eb07c2f")]
            public virtual RepoItemInfo SignInInfo
            {
                get
                {
                    return _signinInfo;
                }
            }
        }

        /// <summary>
        /// The FrmMainAppFolder folder.
        /// </summary>
        [RepositoryFolder("cfcd86cd-7df9-42de-93f8-236376121663")]
        public partial class FrmMainAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _createrequisitionInfo;
            RepoItemInfo _newordersInfo;
            RepoItemInfo _releaserow0Info;
            RepoItemInfo _ribbonInfo;

            /// <summary>
            /// Creates a new FrmMain  folder.
            /// </summary>
            public FrmMainAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FrmMain", "/form[@controlname='FrmMain']", parentFolder, 30000, null, true, "cfcd86cd-7df9-42de-93f8-236376121663", "")
            {
                _createrequisitionInfo = new RepoItemInfo(this, "CreateRequisition", "element[@controlname='ribbon']//toolbar[@accessiblename='Stock Requisitions']/button[@accessiblename='Create Requisition']", 30000, null, "71d94efc-ab09-44ff-893d-d73d65324046");
                _newordersInfo = new RepoItemInfo(this, "NewOrders", "?/?/form[@controlname='FrmBoards']/?/?/container[@controlname='splitControl']/container[@controlname='panel1']//text[@accessiblename='New Orders']", 30000, null, "1eaa0f05-3093-4151-b9a7-fc5d98b270eb");
                _releaserow0Info = new RepoItemInfo(this, "ReleaseRow0", "?/?/form[@controlname='FrmBoards']/?/?/container[@controlname='splitControl']/container[@controlname='panel2']/?/?/container[@controlname='xtbNewOrders']//element[@controlname='gcPOWaitingRelease']/table[@accessiblerole='Table']//cell[@accessiblename='Release row 0']", 30000, null, "027cb7dd-50ff-4da7-a3b0-7ed2604868ec");
                _ribbonInfo = new RepoItemInfo(this, "Ribbon", "element[@controlname='ribbon']", 30000, null, "437f22d9-032c-405e-8a0a-03a9b1656a4f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cfcd86cd-7df9-42de-93f8-236376121663")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cfcd86cd-7df9-42de-93f8-236376121663")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CreateRequisition item.
            /// </summary>
            [RepositoryItem("71d94efc-ab09-44ff-893d-d73d65324046")]
            public virtual Ranorex.Button CreateRequisition
            {
                get
                {
                    return _createrequisitionInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CreateRequisition item info.
            /// </summary>
            [RepositoryItemInfo("71d94efc-ab09-44ff-893d-d73d65324046")]
            public virtual RepoItemInfo CreateRequisitionInfo
            {
                get
                {
                    return _createrequisitionInfo;
                }
            }

            /// <summary>
            /// The NewOrders item.
            /// </summary>
            [RepositoryItem("1eaa0f05-3093-4151-b9a7-fc5d98b270eb")]
            public virtual Ranorex.Text NewOrders
            {
                get
                {
                    return _newordersInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NewOrders item info.
            /// </summary>
            [RepositoryItemInfo("1eaa0f05-3093-4151-b9a7-fc5d98b270eb")]
            public virtual RepoItemInfo NewOrdersInfo
            {
                get
                {
                    return _newordersInfo;
                }
            }

            /// <summary>
            /// The ReleaseRow0 item.
            /// </summary>
            [RepositoryItem("027cb7dd-50ff-4da7-a3b0-7ed2604868ec")]
            public virtual Ranorex.Cell ReleaseRow0
            {
                get
                {
                    return _releaserow0Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ReleaseRow0 item info.
            /// </summary>
            [RepositoryItemInfo("027cb7dd-50ff-4da7-a3b0-7ed2604868ec")]
            public virtual RepoItemInfo ReleaseRow0Info
            {
                get
                {
                    return _releaserow0Info;
                }
            }

            /// <summary>
            /// The Ribbon item.
            /// </summary>
            [RepositoryItem("437f22d9-032c-405e-8a0a-03a9b1656a4f")]
            public virtual Ranorex.Unknown Ribbon
            {
                get
                {
                    return _ribbonInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Ribbon item info.
            /// </summary>
            [RepositoryItemInfo("437f22d9-032c-405e-8a0a-03a9b1656a4f")]
            public virtual RepoItemInfo RibbonInfo
            {
                get
                {
                    return _ribbonInfo;
                }
            }
        }

        /// <summary>
        /// The FrmCreateRequisitionAppFolder folder.
        /// </summary>
        [RepositoryFolder("e601b729-5bb5-46a5-b59e-a17cbf750ccc")]
        public partial class FrmCreateRequisitionAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _openInfo;
            RepoItemInfo _open1Info;
            RepoItemInfo _addrequisitionInfo;
            RepoItemInfo _confirmInfo;

            /// <summary>
            /// Creates a new FrmCreateRequisition  folder.
            /// </summary>
            public FrmCreateRequisitionAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FrmCreateRequisition", "/form[@controlname='FrmCreateRequisition']", parentFolder, 30000, null, true, "e601b729-5bb5-46a5-b59e-a17cbf750ccc", "")
            {
                _openInfo = new RepoItemInfo(this, "Open", "?/?/element[@controlname='ddlLocation']/?/?/button[@accessiblename='Open']", 30000, null, "4bef505e-187d-41b0-80c1-24ab886b769a");
                _open1Info = new RepoItemInfo(this, "Open1", "?/?/element[@controlname='ddlProfileItem']/?/?/button[@accessiblename='Open']", 30000, null, "b3b5db1a-9f41-4913-b863-c75f15835248");
                _addrequisitionInfo = new RepoItemInfo(this, "AddRequisition", "?/?/element[@controlname='btnCreateRequisition']/button[@accessiblename='Add Requisition']", 30000, null, "a636d6a7-4062-4123-bcdf-5e762ad8f373");
                _confirmInfo = new RepoItemInfo(this, "Confirm", "?/?/element[@controlname='btnConfirm']/button[@accessiblename='Confirm']", 30000, null, "238061ca-1ec3-4340-8864-22c0d2d228bd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e601b729-5bb5-46a5-b59e-a17cbf750ccc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e601b729-5bb5-46a5-b59e-a17cbf750ccc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("4bef505e-187d-41b0-80c1-24ab886b769a")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("4bef505e-187d-41b0-80c1-24ab886b769a")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The Open1 item.
            /// </summary>
            [RepositoryItem("b3b5db1a-9f41-4913-b863-c75f15835248")]
            public virtual Ranorex.Button Open1
            {
                get
                {
                    return _open1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open1 item info.
            /// </summary>
            [RepositoryItemInfo("b3b5db1a-9f41-4913-b863-c75f15835248")]
            public virtual RepoItemInfo Open1Info
            {
                get
                {
                    return _open1Info;
                }
            }

            /// <summary>
            /// The AddRequisition item.
            /// </summary>
            [RepositoryItem("a636d6a7-4062-4123-bcdf-5e762ad8f373")]
            public virtual Ranorex.Button AddRequisition
            {
                get
                {
                    return _addrequisitionInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddRequisition item info.
            /// </summary>
            [RepositoryItemInfo("a636d6a7-4062-4123-bcdf-5e762ad8f373")]
            public virtual RepoItemInfo AddRequisitionInfo
            {
                get
                {
                    return _addrequisitionInfo;
                }
            }

            /// <summary>
            /// The Confirm item.
            /// </summary>
            [RepositoryItem("238061ca-1ec3-4340-8864-22c0d2d228bd")]
            public virtual Ranorex.Button Confirm
            {
                get
                {
                    return _confirmInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Confirm item info.
            /// </summary>
            [RepositoryItemInfo("238061ca-1ec3-4340-8864-22c0d2d228bd")]
            public virtual RepoItemInfo ConfirmInfo
            {
                get
                {
                    return _confirmInfo;
                }
            }
        }

        /// <summary>
        /// The GenesisAutomationAppFolder folder.
        /// </summary>
        [RepositoryFolder("51d12379-fb49-4f4b-ba80-e2fe15df1ee0")]
        public partial class GenesisAutomationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _descriptionrow9Info;
            RepoItemInfo _descriptionrow0Info;

            /// <summary>
            /// Creates a new GenesisAutomation  folder.
            /// </summary>
            public GenesisAutomationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GenesisAutomation", "/form[@title='']", parentFolder, 30000, null, true, "51d12379-fb49-4f4b-ba80-e2fe15df1ee0", "")
            {
                _descriptionrow9Info = new RepoItemInfo(this, "DescriptionRow9", "container[@controlname='SearchEditLookUpPopup']/container[@controlname='lc']//row[@accessiblename='Row 10']/cell[@accessiblename='Description row 9']", 30000, null, "c54e82c9-42d8-4ab3-98ac-9731fd72820e");
                _descriptionrow0Info = new RepoItemInfo(this, "DescriptionRow0", "container[@controlname='SearchEditLookUpPopup']/container[@controlname='lc']//row[@accessiblename='Row 1']/cell[@accessiblename='Description row 0']", 30000, null, "bb4ca6fc-b1b3-49cc-ad55-fba06d2d5f4b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("51d12379-fb49-4f4b-ba80-e2fe15df1ee0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("51d12379-fb49-4f4b-ba80-e2fe15df1ee0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DescriptionRow9 item.
            /// </summary>
            [RepositoryItem("c54e82c9-42d8-4ab3-98ac-9731fd72820e")]
            public virtual Ranorex.Cell DescriptionRow9
            {
                get
                {
                    return _descriptionrow9Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The DescriptionRow9 item info.
            /// </summary>
            [RepositoryItemInfo("c54e82c9-42d8-4ab3-98ac-9731fd72820e")]
            public virtual RepoItemInfo DescriptionRow9Info
            {
                get
                {
                    return _descriptionrow9Info;
                }
            }

            /// <summary>
            /// The DescriptionRow0 item.
            /// </summary>
            [RepositoryItem("bb4ca6fc-b1b3-49cc-ad55-fba06d2d5f4b")]
            public virtual Ranorex.Cell DescriptionRow0
            {
                get
                {
                    return _descriptionrow0Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The DescriptionRow0 item info.
            /// </summary>
            [RepositoryItemInfo("bb4ca6fc-b1b3-49cc-ad55-fba06d2d5f4b")]
            public virtual RepoItemInfo DescriptionRow0Info
            {
                get
                {
                    return _descriptionrow0Info;
                }
            }
        }

        /// <summary>
        /// The GenesisAutomation1AppFolder folder.
        /// </summary>
        [RepositoryFolder("509ff017-4497-44fc-8951-e4ad111bb67a")]
        public partial class GenesisAutomation1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new GenesisAutomation1  folder.
            /// </summary>
            public GenesisAutomation1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GenesisAutomation1", "/form[@title='Genesis Automation']", parentFolder, 30000, null, true, "509ff017-4497-44fc-8951-e4ad111bb67a", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "?/?/button[@accessiblename='&OK']", 30000, null, "e546c0a6-b843-4955-a53d-b9ac7645a410");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("509ff017-4497-44fc-8951-e4ad111bb67a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("509ff017-4497-44fc-8951-e4ad111bb67a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("e546c0a6-b843-4955-a53d-b9ac7645a410")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("e546c0a6-b843-4955-a53d-b9ac7645a410")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The PurchaseOrderAppFolder folder.
        /// </summary>
        [RepositoryFolder("285e36c0-a8bf-490b-9839-f0d08abfb535")]
        public partial class PurchaseOrderAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new PurchaseOrder  folder.
            /// </summary>
            public PurchaseOrderAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PurchaseOrder", "/form", parentFolder, 30000, null, true, "285e36c0-a8bf-490b-9839-f0d08abfb535", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "?/?/button[@accessiblename='&OK']", 30000, null, "2e75d139-f613-4d99-adef-5a75a4152411");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("285e36c0-a8bf-490b-9839-f0d08abfb535")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("285e36c0-a8bf-490b-9839-f0d08abfb535")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("2e75d139-f613-4d99-adef-5a75a4152411")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("2e75d139-f613-4d99-adef-5a75a4152411")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
